name: Hello World
on: [push]

jobs:
  ci:
    strategy:
      matrix:
        number: ['1', '2', '3', '4']

    runs-on: self-hosted

    steps:
      - run: sleep 300; echo Hello ${{ matrix.number }}
